### ISSUE TITLE
How to pass parameter to eval so .m file will return an image?

### ISSUE THREAD

**Issue by schreiby** [shannah/CN1ObjCBridge#1]
Hello, 

I am trying to create a PeerComponent with this library but am getting the following error when building: 

`Exception: com.codename1.objc.Objc.ObjectiveCException - Exception while processing Objective-C expression [GetImageFromPDF.start:] on target Obj`

I am trying to call a `.m` file that I put in the native/iOS folder as you indicated. In the sample HelloWorld.m there is no parameter to pass in. I need to pass a path to my .m file so I can generate an UIImage for iOS. Is this the correct way to implement this library:

` return Objc.createPeerComponent(()->{`
            `    Pointer image = eval("GetImage.go:", path).asPointer();`
            `    return image;`
        `   });`

Or am I misunderstanding how PeerComponent works?

Thanks.

**Comment by shannah** [comment]
Can you post your HelloWorld.m file so I can see the objective-c API that you're trying to use.

**Comment by schreiby** [comment]
Thanks. Instead of passing trying to generate a PeerComponent, I used a native interface (which I'm more accustomed to doing) and returned a byte[] as NSData. I'm going to study your library some more so I can use it in my code. Thank you again.
