### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by schreiby** [shannah/CN1ObjCBridge#4]
Hi, 

I saw on the CN1 plugins page that this library is licensed under the BSD license. Is there a specific way you'd like to be credited in our app?

Thank you.

**Comment by shannah** [comment]
I've added a license file

https://github.com/shannah/CN1ObjCBridge/commit/2d932ddca0851a2e27c5147642814d873239f564

Thank you for asking.  There is no credit required, but if you have some sort of "credits" page, and you want to include a credit, it is appreciated.
